### ISSUE TITLE
TensorFlow Documentation

### ISSUE THREAD

**Issue by vaibhavi-d18** [Mozilla-Campus-Club-Cummins/Documentation_HacktoberFest24#29]
This document outlines the ResNet-18 model, focusing on its residual learning architecture, key features, training process, and applications in tasks like image classification and object detection. It highlights the model's efficiency, ease of training, and versatility for transfer learning.

**Comment by vaibhavi-d18** [comment]
Hello, I want to work on this issue. could you please assign this issue to me?

**Comment by ananahyeah** [comment]
you will get 2 days to work on this
thank you
